[features]
seeds = false
[programs.localnet]
test_pda_fpa = "Gm15Qkbc3DZRozPn2xy6cXe8X77U4zza3NYyxSkUTZaU"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
