[features]
seeds = false
[programs.localnet]
test_pda_fpa = "7ZGin1cH6HnZM19J9ovXXn3FyaheRQoAK83okRzqyiXf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/user/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
